### ISSUE TITLE
Can't get it to work under node js

### ISSUE THREAD

**Issue by krasi0** [surfinzap/typopo#12]
A node js newbie here. 
I've created a new file test.mjs on Linux
with the following contents:
-------------------------------
import { fixTypos } from typopo;

// console.log(fixTypos);
console.log(fixTypos("itt's there", "en-us"));
-------------------------------
I am executing the file using:
~ $ node --experimental-modules test.mjs 
(node:429) ExperimentalWarning: The ESM module loader is experimental.
file:///home/node/test.mjs:1
import { fixTypos } from typopo;
                         ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:51:18)
    at async link (internal/modules/esm/module_job.js:38:36)

================================
I've tried various options like downloading typopo.min.js, using `require()` instead of `import` but nothing seems to work. 
Any advice on how to get your awesome library to work under a new node js project? Thanks! :)

**Comment by surfinzap** [comment]
Hi @krasi0, since [version 2.3.1](https://github.com/surfinzap/typopo/releases/tag/2%2F3%2F1) you can now use typopo as a part of a Node.js project. Let me know, when you ran into any issues.
